[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000262FFEB5DE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f20b5aad9bf4044b96fc84c31bf0ba79
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000262FFEB6710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f20b5aad9bf4044b96fc84c31bf0ba79
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000262FFEB6890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f20b5aad9bf4044b96fc84c31bf0ba79